# version: '3.8'
#MongoDB 5.0+ requires a CPU with AVX support, => sử dụng image: mongo:4.4
services:
  db-mongo:
    image: mongo:6.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    expose:
      - 27017

  be-nest:
    build:
      context: ./NestJS
      dockerfile: Dockerfile
    # restart: unless-stopped
    environment:
      - PORT=8000
      - NODE_ENV=production
      - MONGO_URL=mongodb+srv://nducanh1010:sy1pzHlQ5VMWXyJ7@cluster0.xpttnn3.mongodb.net/ducanh
      # - DB_HOST=host.docker.internal
    expose:
      - 8000
    ports:
      - 8000:8000
  fe-nest:
    build:
      context: ./FE_NestJs
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      #tham số sẽ override và ghi đè file .env
      - VITE_ENV=production
    expose:
      - 3000
    ports:
      - 3001:3000
volumes:
  mongodb:
